name: Branch Deployment

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  quality-gate:
    uses: ./.github/workflows/quality-gates-workflow.yml

  deploy-data-migrations:
    name: Run Data Migrations
    runs-on: ubuntu-latest
    needs: [ quality-gate ]
    environment: 
      name: nonprod
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 16.x
      - uses: ./.github/workflows/composite/data-migrations
        with:
          stage: nonprod
          config: ${{ secrets.AWS_CONFIG }}
          credentials: ${{ secrets.AWS_CREDENTIALS }}

  deploy-infrastructure-and-app:
    name: Deploy App & Infra
    runs-on: ubuntu-latest
    needs: [ deploy-data-migrations ]
    environment:
      name: nonprod
    steps:
      - uses: actions/checkout@v3
        with:
            node-version: 16.x
      - uses: ./.github/workflows/composite/aws-connected-command
        with:
          command: npm run deploy:nonprod
          config: ${{ secrets.AWS_CONFIG }}
          credentials: ${{ secrets.AWS_CREDENTIALS }}


- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT